image:
  repository: ghcr.io/elreplicante/fastapi-hello-helm
  tag: "1.0.0"
  pullPolicy: IfNotPresent

fullname: fastapi-hello-helm

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: hello.local
      paths:
        - /
