apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-fastapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elreplicante/fastapi-hello-helm.git
    targetRevision: main
    path: chart/hello-fastapi
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true