apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-hello-helm
  labels: {{- include "fastapi-hello-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "fastapi-hello-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "fastapi-hello-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        { { - range .Values.image.pullSecrets } }
        - name: { { . } }
        { { - end } }