apiVersion: v1
kind: Service
metadata:
  name: fastapi-hello-helm
  labels: {{- include "fastapi-hello-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector: {{- include "fastapi-hello-helm.selectorLabels" . | nindent 4 }}